site_name: wg-access-server
strict: true
repo_name: sharekey/wg-access-server
repo_url: https://github.com/sharekey/wg-access-server
site_url: https://sharekey.github.io/wg-access-server/

theme:
  name: material
  include_sidebar: true
  icon:
    logo: material/cloud-outline # alias: cloud-queue
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: light blue
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - markdown_include.include:
      base_path: docs
  - meta
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: " ¶"

plugins:
  - search
